apiVersion: apps/v1
kind: Deployment
metadata:
name: nexus-registry
labels:
    app: nexus-registry
spec:
replicas: 2
selector:
    matchLabels:
    app: nexus-registry
template:
    metadata:
    labels:
        app: sonatype-registry
    spec:
    volumes:
    - name: nexus-vol
        persistentVolumeClaim:
        claimName: nexus-pvc
    containers:
    - image: sonatype/nexus3
    name: nexus
    ports:
        - containerPort: 8081
    volumeMounts:
    - name: nexus-vol
        mountPath: /nexus-data
        subPath: sonatype