apiVersion: v1i
kind: PersistentVolume
metadata:
name: nexus-pv
labels:
    name: nexus-pv # claim for volume
spec:
storageClassName: nexus-storage # same storage class as pvc
capacity:
    storage: 40Gi
accessModes:
    - ReadWriteOnce
nfs:
    server: 192.168.40.8 # ip addres of nfs server
    path: "/mnt/nfs-volume"  # path to directory, make sure directory is availablei
