apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops-tools
spec:
  selector:
    app: nexus-server
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 32323
  type: NodePort
